/// The type of a LaTeX element.
enum LEType {
  trunk,
  node,
  leaf,
  // Node types
  functionNode,
  inverseFunctionNode,
  fractionNode,
  numeratorNode,
  denominatorNode,
  squareRootNode,
  cubeRootNode,
  nthRootNode,
  indexOfRootNode,
  radicandNode,
  powerNode,
  lowerLimitNode,
  upperLimitNode,
  integrandNode,
  integralNode,
  summandNode,
  summationNode,
  // Leaf types
  placeHolderLeaf,
  numberLeaf,
  operatorLeaf,
  variableLeaf,
  symbolLeaf,
  specialSymbolLeaf,
  textLeaf,
}
